language: csharp
solution: FOWeb4/FOWeb4.sln

env:
  global:
    - "FTP_USER=FOSimple\\sheikp"
    - "FTP_PASSWORD=rayhan2006"
after_success:
    "curl --ftp-create-dirs -T FOWeb4/FOWeb4/Default.aspx -u $FTP_USER:$FTP_PASSWORD ftp://waws-prod-sn1-011.ftp.azurewebsites.windows.net/site/wwwroot"
    
